version: "3.9"

services:
  db:
    image: postgres:16.3
    env_file: ./.env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4.8.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  migrator:
    build: ./migrator
    env_file: ./.env.dev
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head"

  collector:
    build: ./services/collector
    env_file: ./.env.dev
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped

  api:
    build: ./services/api
    env_file: ./.env.dev
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  streamlit:
    build: ./services/ui/streamlit
    env_file: ./.env.dev
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  pgdata:
